spring:
  profiles:
    active: production
  datasource:
    url: jdbc:postgresql://localhost:5432/weather # should be production url
    driver-class-name: org.postgresql.Driver
    sql-script-encoding: UTF-8
    hikari:
      maximum-pool-size: 10