# Default application context, usually used to run locally
server:
  port: 8080
  compression:
    enabled: true
spring:
  jmx:
    enabled: false
  profiles:
    active: default
  jpa:
    show-sql: false # Show or not log for each sql query
    open-in-view: false
    hibernate:
      ddl-auto: none # Hibernate ddl auto, to be executed by flyway instead
      use-new-id-generator-mappings: false
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.temp.use_jdbc_metadata_defaults: true
  flyway:
    encoding: UTF-8
    locations:
      - classpath:/db/migration/core
    table: FLYWAY
weather-api:
  url: http://api.openweathermap.org/data/2.5/weather
  appid:
weather-scheduler:
  enabled: true
  delay-millis: 120000 # 2 minutes
  initial-delay-millis: 2000
  limit: 300